#!/bin/bash

linkdots() {

	local DOTFILES="${HOME}"/.dotfiles
	local ROOT=/root

	LINK_USER_DOTS() {
		ln -snf "${DOTFILES}"/bashrc "${HOME}"/.bashrc
		ln -snf "${DOTFILES}"/bash_profile "${HOME}"/.bash_profile
		ln -snf "${DOTFILES}"/bash_logout "${HOME}"/.bash_logout
		ln -snf "${DOTFILES}"/bash.d "${HOME}"/.bash.d
		ln -snf "${DOTFILES}"/compton.conf "${HOME}"/.compton.conf
		ln -snf "${DOTFILES}"/config "${HOME}"/.config
		ln -snf "${DOTFILES}"/gtkrc-2.0 "${HOME}"/.gtkrc-2.0
		ln -snf "${DOTFILES}"/i3 "${HOME}"/.i3
		ln -snf "${DOTFILES}"/scripts "${HOME}"/.scripts
		ln -snf "${DOTFILES}"/xinitrc "${HOME}"/.xinitrc
		ln -snf "${DOTFILES}"/Xresources "${HOME}"/.Xresources
		# shellcheck disable=SC1091
		source /home/loki/.bashrc
		echo "Dotfiles Linked! (\",)"
	};

	LINK_ROOT_DOTS() {
		sudo ln -snf "${DOTFILES}"/root/bashrc "${ROOT}"/.bashrc
		sudo ln -snf "${DOTFILES}"/root/bash_profile "${ROOT}"/.bash_profile
		sudo ln -snf "${DOTFILES}"/root/bash.d "${ROOT}"/.bash.d            
		sudo ln -snf "${DOTFILES}"/root/scripts "${ROOT}"/.scripts
		# shellcheck disable=SC1091
		echo "Dotfiles Linked! (\",)"
	};

	for command in "$@"
	do
		case $command in
			u|user)
				LINK_USER_DOTS
			;;
			r|root)
				LINK_ROOT_DOTS
			;;
			a|all)
				LINK_USER_DOTS
				LINK_ROOT_DOTS
			;;
			!*)
				LINK_USER_DOTS
				LINK_ROOT_DOTS				
			;;
			*)
				echo $"Usage: $0 {user|root|all}"
			;;
		esac
	done
};
