#!/bin/bash

function INSTALL_I3_LOCK {
	sudo apt update
	sudo apt-get install -y	pkg-config \
				libxcb1 \
				libxcb-dev \
				libxcb-dpms0-dev \
				libxcb-image0-dev \
				libxcb-util0-dev \
				libxcb-xkb-dev \
				libxcb-randr \
				libxcb-composite0 \
				libxcb-composite0-dev \
				libxcb-xinerama0-dev \
				libev-dev \
				libx11-dev \
				libx11-xcb-dev \
				libpam-dev \
				libcairo2-dev \
				libfontconfig-dev \
				libjpeg-turbo \
				libxkbcommon0 \
				libxkbcommon-x11-0 \
				libxkbfile-dev \
				libxkbcommon-x11-dev \
				libxkbcommon-dev \
				imagemagick \
				awk \
				util-linux \
				wmctrl \
				scrot \
				maim
				
	cd /tmp
	git clone https://github.com/PandorasFox/i3lock-color.git
	cd i3lock-color
	git tag -f "git-$(git rev-parse --short HEAD)"
	autoreconf -i
	./configure --prefix=/usr/local/
	make
	sudo make install
	
	
	cat >>EOF
	[Unit]
	Description=Lock the screen automatically after a timeout
	
	[Service]
	Type=simple
	User=meskarune
	Environment=DISPLAY=:0
	ExecStart=/usr/bin/xautolock -time 5 -locker /usr/local/bin/lock/lock -detectsleep
	
	[Install]
	WantedBy=graphical.target
	EOF
